export const USER_INFO = 'USER_INFO';
export const USER_SETTING = 'USER_SETTING';
export const USER_FAV = 'USER_FAV';
export const USER_TOGGLE_FAV = 'USER_TOGGLE_FAV';
export const USER_FAV_DETAIL = 'USER_FAV_DETAIL';
export const USER_FAV_DETAIL_UPDATE = 'USER_FAV_DETAIL_UPDATE';

export const BOOK_HOT_LIST = 'BOOK_HOT_LIST';
export const BOOK_CATEGORY_LIST = 'BOOK_CATEGORY_LIST';
export const BOOK_LIST_BY_CATEGORY = 'BOOK_LIST_BY_CATEGORY';

export const DEVICE_INFO = 'DEVICE_INFO';
