<template>
  <div>
    <mt-header
      title="注册"
    >
      <mt-button
        icon="back"
        slot="left"
        @click="$router.back()"
      ></mt-button>
    </mt-header>
    <mt-field
      label="用户名"
      class="mbottom10"
      placeholder="请输入用户名"
      v-model="account"
    ></mt-field>
    <mt-field
      label="邮箱"
      class="mbottom10"
      placeholder="请输入邮箱"
      type="email"
      v-model="email"
    >
    </mt-field>
    <mt-field
      label="密码"
      class="mbottom10"
      placeholder="请输入密码"
      type="password"
      v-model="password"
    >
    </mt-field>
    <mt-button
      type="primary"
      size="large"
      :style="{
        marginTop: '30px',
      }"
      @click="submit"
    >提交</mt-button>
  </div>
</template>

<script src="./register.js">
</script>
